### PR TITLE
Added collaborator information query to dependency info

### PR DESCRIPTION
**Pull request by IanLee1521**
The intent here is to gather information about who contributes to our open source projects (and their dependencies).

@LRWeber -- I checked this in teh graphql explorer, but I've done very little overall with graphql, so would appreciate a second set of :eyes:

### CODE REVIEW

**Review by LRWeber — CHANGES_REQUESTED** [review]
Unfortunately, our queries don't appear to have permission to view collaborators for repos that we do not own. They all come back with errors, so the info gets tossed out, leaving only `LLNL/scraper` in our `dependencyInfo.json` file.

For our own projects, we already have info in `extUsers.json`. But I don't think we'll be able to expand on that kind of info at the dependency level.

**Comment by IanLee1521** [comment]
Ah, yes, you're right, that probably won't work then.. I guess I'm surprised we can't get external project info this way since it's part of their public data when you browse around a repo..

**Comment by LRWeber** [comment]
@IanLee1521 You may be looking for `mentionableUsers` as the public information rather than `collaborators`. This is what we've been using for our other cases.
However, this will be a more in depth change requiring pagination, including modifications to `get_dependency_info.py` to support it.

**Comment by IanLee1521** [comment]
Ah, thanks @LRWeber I think you're right. I'm going to cancel this since it doesn't do what I thought it would do. (was a bit more hypothetical anyways).

**Pull request closed without merging**
