### PR TITLE
Introducing RADIUSS policies and guidelines

### PR DESCRIPTION
**Pull request by adrienbernede**
RADIUSS policies and guidelines are introduced in Markdown format.
The main page (radiuss-policies-guidelines.md) contains a short,
accessible version of the Mandatory and Recommended points with links to
the detailed versions.
The policies-guidelines.md contains on file per category, gathering the
detailed versions for each M & R.

### CODE REVIEW

**Comment by LRWeber** [comment]
Does this mean we should close #186 ?

**Comment by hauten** [comment]
> Does this mean we should close #186 ?

Probably, but I want to give this a quick editorial pass & see how it's organized. @adrienbernede and I had kicked around a couple of ideas and, w/o looking at it yet, I'm not sure how it ended up. I'm sure it's all fine! Will review as soon as I can.

**Comment by adrienbernede** [comment]
The pull request is to replace the other #186 yes. But it need some "finalization" work.

**Comment by adrienbernede** [comment]
I forgot references.
@hauten instead of having one file per recommendation, I ended up with one per category.
As we discussed, all this could land in the same web-page with "jumps".

**Comment by adrienbernede** [comment]
I just added the missing references and external links.

**Comment by hauten** [comment]
@IanLee1521 & @adrienbernede see my latest commit [18d3be2](https://github.com/LLNL/llnl.github.io/pull/236/commits/18d3be224ca828c71938b6eee8df9fa71f4e15eb).

- Renamed index.md & "Policies" directory
- Updated links accordingly
- Applied page layout
- Lightly edited
- Added "Policies" to site header

I wasn't sure if I should add a permalink to each subpage. News and Archive have it but not the About pages. Necessary?

I remain on the fence about whether to include a "back to Policies home" (or similar link) at the top of the subpages. We aren't showing those pages in the site header, so the only way to get back to the parent page is to go back in your browser or to navigate to RADIUSS > Policies.

**Comment by adrienbernede** [comment]
@hauten The links in the index are not working in the github interface. I guess this is because it written so that it works on the website, not on the repo. Right ?

**Comment by adrienbernede** [comment]
The "back to Policies home" will be unnecessary as soon as the menu will be in place right ?

**Comment by hauten** [comment]
> @hauten The links in the index are not working in the github interface. I guess this is because they are written so that it works on the website, not on the repo. Right ?

Yep, they worked locally as relative URLs

> The "back to Policies home" will be unnecessary as soon as the menu will be in place right ?

Yes, when the have the "fancy" menu in place. But for now, there's no breadcrumb back up a level from, say, Documentation to the parent P&G page.

**Comment by adrienbernede** [comment]
OK, if adding a link back to the P&G page it a one-line thing I can pretty easily had it to all sub-pages. 
You don’t like it because it would be temporary ?

**Comment by hauten** [comment]
> OK, if adding a link back to the P&G page it a one-line thing I can pretty easily had it to all sub-pages.
> You don’t like it because it would be temporary ?

I don't like it b/c we don't do it anywhere else. BUT we also don't have pages with these relationships anywhere else. So it's fine. Under {: .page-header}:
`[Back to Policies and Guidelines home](/radiuss/policies/)`

**Comment by adrienbernede** [comment]
Once this branch is merged we can create an issue for the menu and reference commit 0d66c32 as "to be reverted".

**Comment by adrienbernede** [comment]
Made a mistake adding too many files, corrected.

**Comment by adrienbernede** [comment]
@IanLee1521 I made some improvements to make the P&G more pleasant to read, and introduce them better. I hope you’ll like the changes (as the first person seeing it). I had the introduction validated by Rob Neely.

**Comment by adrienbernede** [comment]
PR is paused for integration of latest changes.

**Comment by IanLee1521** [comment]
If the PR is paused, why close it?

**Comment by adrienbernede** [comment]
Didn’t how to do differently

**Comment by IanLee1521** [comment]
No worries, there isn't really a set way.

I did just make a new "DO NOT MERGE" label though. Maybe in the fullness of time we can add that in to our bot checks? (cc/ @LRWeber)

**Comment by adrienbernede** [comment]
Need some help to solve conflicts on header.html, or will have to wait for some free brain time. :p

**Comment by adrienbernede** [comment]
Thanks @hauten for your help with the merge. @IanLee1521 the label `do not merge` can now be remove. This is ready for review.

**Comment by adrienbernede** [comment]
Thanks @IanLee1521

**Comment by neely4** [comment]
@IanLee1521 @adrienbernede @hauten - I'm not sure why there's a conflict with those conflicting files, I don't think they were modified in this branch (that I know of). Can anyone help resolve this so we can get this PR merged up?

**Comment by adrienbernede** [comment]
@neely4 There is no more conflicts now. They were small anyway. The PR is ready as far as I can tell. You may want to quickly review these changes https://github.com/LLNL/llnl.github.io/pull/236/commits/a0cfd1ec38f52fd5bb1a6ba02d6655880d651060
And that’s it.

**Comment by neely4** [comment]
Thanks @adrienbernede. I don't use GitHub enough to know all the end cases, but this PR still has a big "Changes requested / Merging is blocked" notice in what I'm seeing, but the requested changes from Ian date back to last August and are no longer relevant. @IanLee1521 - are you OK with this branch as is?

**Pull request merged**
