### PR TITLE
Added Popular Repos List

### PR DESCRIPTION
**Pull request by aidan-epperly**
Adds a numbered list of popular repos to the beginning of the page.
image

### CODE REVIEW

**Comment by LRWeber** [comment]
It seems a bit redundant to have virtually identical titles over the text rankings and the circle graph. We could probably combine the two. Maybe displayed side by side?

**Comment by aidan-epperly** [comment]
Does this work?
image
Putting them next to each other is more complex.

**Comment by LRWeber** [comment]
That would work.

**Comment by LRWeber** [comment]
The `#`s in the list may be unnecessary, and just add visual clutter.
We may also need a way to visually separate the rankings from the names, such as bold text, additional separating character, etc.

It might also be more engaging if the ranking list included links to each repo's individual stat page! (e.g. https://software.llnl.gov/repo/#/openzfs/zfs)

**Comment by aidan-epperly** [comment]
Changed numbering style:
image

**Comment by aidan-epperly** [comment]
Bold:
image

**Comment by IanLee1521** [comment]
I like the new style with the bold.

**Comment by aidan-epperly** [comment]
Links:
image

**Comment by aidan-epperly** [comment]
I believe that is all of the edits that were talked about.

**Comment by aidan-epperly** [comment]
image

**Comment by aidan-epperly** [comment]
I think there may have been an issue with the squash?

**Comment by aidan-epperly** [comment]
No, it seems to be a different issue. I don't really know why it is doing that. It looks like an issue with how github pages deployed it.

**Pull request merged**
