### PR TITLE
Updating organization and navigation of site

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will do a bit of re-organization and nativation changes to make the interface a little easier for a newcomer to find what they are looking for. Specifically:

**pages** are now all represented under the "pages" directory. Browsing the site as a new developer, it was a bit confusing to try and distinguish data from collections from other content. By placing all website pages under pages, I know where to look for it, and the organization reflects nesting on the site.

**search/explore vs. visualize** The current "explore" button threw me off because I always expected the browser / search view. I have changed this link to be Visualize, and the search view at the top is "browse projects," which I suspect some people will jump to immediately.

**RADIUSS** is really about policy and guidelines. It was presented on the site as a heading, and I do not think a visitor to the site that is not familiar with the lab will really understand what it is, and why it is there. I also found that showing another "search" or "browse" interface under RADIUSS was confusing. What made sense was to remove this redundant view, and then move radius to be under about, and specifically under the heading of "Policy and Guidelines." That is exactly what RADIUSS is to some of these projects, and it makes sense to put it there in context of the site. Now if there does need to be someting to distinguish radiuss from non RADIUSS projects we could do a badge or something. but with this refactor, it is not confusing to have more than one search view, and RADIUSS is better understood in context of the site.

**spelling** I am loving this action to check spelling on PRs - it shows the developer any spelling errors to fix! It can be run locally like a linted to fix spelling errors too. I have added notes to the READMe about using it. The _typos.toml file has words that need to be ignored. Interesting, one of the podcast links for spack has a spelling mistake (so "epsiode" is added). They don't have issues on their repo so I couldn't open one.

**preview** we need a good way to preview the site when there are changes! I have added a Circle build that has worked well for me across many sites, someone with super admin powers will need to connect the repository! This is especially important because I'm worried that I missed a page / resource file path when I updated the organization!

I hope this is a slight help to the organization / structure of the site! Looking forward to doing more. I think it will be quite a bit more work to add more description / use cases for repos but if I do it anyway for this other project I want to do called contributor CI, it won't technically be any extra work!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by hauten** [comment]
Generally I like this, and it's great to get a fresh perspective on a site I've been involved with for a few years. I defer to the real developers among us about what makes the repo easier to navigate (e.g., the `pages` folder).

Correct that the spellchecker is looking at code, not at text the user sees (e.g., the text of a news post)? We are using the Lab's Site Improve crawler to check for typos and broken links, among other things. It wouldn't have caught the Floss for Science link typo b/c the link isn't broken.

Explore --> Visualize: I agree this makes more sense as a name for that area of the site.

"Browse projects" as a navigation cue: What about "Catalog" instead? I say that b/c we use that nomenclature elsewhere on the site. There are folders for `explore` and `_explore`, which may be why the browse is broken? Should the URL path for this area match the nav bar name?

Where to put RADIUSS: I am fine with RADIUSS simply being part of the main catalog, but one of the original requirements from Rob was to give it its own space. In recently building out a dedicated RADIUSS space on dev.llnl.gov, the external-facing RADIUSS area of this site was revisited -- but not yet in light of *these* suggestions.

Moving RADIUSS and eliminating its own browse page = we need to find and update the links to these things, not just on this site (e.g., FAQ refers to it) but elsewhere like dev.llnl.gov. Or set up redirects, which I don't know how to do on GitHub pages and haven't yet researched. (My preference is to change the links where we can and establish redirects to catch those we can't.) Also need to check if the RADIUSS README needs updating.

I made one change to remove the P&G link from it's own page. Now that I'm tracking to this branch, I'm happy to help make other changes, pending @IanLee1521 feedback.

**Comment by vsoch** [comment]
@hauten I know how to do redirects! If you can tell me which urls should have them, I can set them up.

**Comment by vsoch** [comment]
And if RADIUSS is the larger effort of "Best practices for open source at the lab" it likely should have it's own site that focuses on those best practices, etc. I think it's good to have it here for now (and makes sense to keep) but akin to how Google has an open source guide: https://opensource.google/docs/ I think we would want another central place for the "LLNL Open source Guide" which is notably different from LLNL open source software (but of course they would likely have the same branding and link to one another, just like opensource.google does.

**Comment by adrienbernede** [comment]
@vsoch thanks for all the suggestions and work. I was thinking maybe some of it could have been in a dedicated PR, this would have kept my comment shorter :).

### RADIUSS:

It is true that, per the current website content, RADIUSS seems to be all about Policies & Guidelines. This was a big effort of discussions between projects to come up with those about 2 years ago.

Since then, we moved our effort to other things, for which I agree we should create more content in order to illustrate the role of RADIUSS for LLNL open-source projects.

- First, RADIUSS provides targeted support to better use other LLNL libraries and tools. Helping projects with the migration to RAJA is a typical example. We could have an achievements section under the RADIUSS heading. I'll defer that suggestion to @davidbeckingsale and @neely4.

- Second, and this is much more familiar to me, we helped projects migrating to LC Gitlab CI. This consisted in setting up mirrors on LC Gitlab, improving/documenting the PR management workflow sometimes, and automatically build dependencies with Spack in CI context.

Content already exists for the second point: https://radiuss-ci.readthedocs.io. I think we should create an introductory page under the radiuss heading, and point to that documentation (which is currently undergoing some revamping with the creation of https://radiuss-spack-testing.readthedocs.io).

That is to say that I think RADIUSS should not be just under the "about" heading, but maybe we need to reconsider the heading (like Docs, per your google example)?

### RADIUSS and pages

Regarding your suggestion based on Google Docs page, I am not sure to understand exactly what you would like.

The link you point to is the "Docs" heading, and there also is a "Projects" one where you can browse projects.
On https://software.llnl.gov/, it's like if we focused on the "Projects" section, and have secondary sections (RADIUSS, News, ...). Do you mean we should have a "Projects" section too?

With your work on "pages", it seems you are doing something similar, although I didn't check the results... I will soon.

If, like I first thought, you meant you think RADIUSS should have a dedicated website, then I am not sure. This would be fragmenting things, and may make RADIUSS less discoverable, while the goal was to advertise for the existence of this project supporting the open source effort at the lab. It would also be more maintenance work.

### preview

I really like the idea of having a version of the website generated through CI, this is typically addressing the need I felt ready your PR comment: I would like to compare both versions, but without having to build it locally (I'm on yet another computer of mine right now).

I am probably being picky, but could this we done with Github Actions? Not a lot of use use Circle CI. I am just thinking that with Github Action, maintenance would be more accessible to any of us.

### The rest

The rest looks good to me :)

**Comment by vsoch** [comment]
> Regarding your suggestion based on Google Docs page, I am not sure to understand exactly what you would like.

Let me see if I can clarify! So the idea of linking https://opensource.google/docs/ is that Google Opensource (that also has projects, note this is not the projects but the docs around them) is that they don't have a random acronym (that people visiting might not understand) but rather they brand the content that talks about policies, licenses, as exactly that - the top heading is "Docs" but we could also just call it what it is, Policies / similar. So the idea is we would have a top level heading like this that is understandable, and then maybe in smaller text on the page something like "This content and support for OSS at LLNL is provided by the RADIUSS project, which means XXX. You can read more about RADIUSS here (and then link to its own docs).

> Do you mean we should have a "Projects" section too?

To be more explicit, I think this navigation:

image

Would be:

Projects (currently Explore)
Policy OR Docs (currently RADIUSS)
News
About

> It would also be more maintenance work. 

I think about this differently - I favor modular development because it's easier to assign responsibility, and not have one massive hairball webpage that has all-the-things!

**Comment by vsoch** [comment]
Oh, and forgot to answer your question! GitHub Actions does not support an in browser preview - you’d either need to download artifacts or offload to another preview service. CircleCI supports in browser view of build artifacts so nothing extra is needed in terms of work or services.

**Comment by adrienbernede** [comment]
@vsoch this is clearer to me. So you don't ask for the RADIUSS content to move somewhere else, but simply to name the section "Policies" if it is meant to contain only the policies.

That seems legitimate to me! Based on may comment above, we have more documentation content we could point to, so maybe "Docs" is a good header, and below that we would have "Policies / Guidelines" "LC Gitlab CI" "Spack testing", etc.

I believe that we could also have a page "RADIUSS" under the "About" section, in which we describe the Project and it's goals.

**Comment by adrienbernede** [comment]
Now, some of that could go to dev.llnl.gov. This needs to be discussed.

**Comment by hauten** [comment]
> Now, some of that could go to dev.llnl.gov. This needs to be discussed.

Yes, need to discuss in re: https://dev.llnl.gov/opensource/radiuss/, which has changed some since this PR was opened

**Comment by hauten** [comment]
I am getting back to this. Not everything is previewing correctly locally b/c of many changes to the site since this PR was created. That said, I think I want to (1) make a few minor changes, (2) merge, and then (3) clean up if anything is broken. Later we can revisit other information not currently on the site (e.g., GitLab, which already lives on an internal site) for appropriateness; focusing right now on existing content.

Among the cleanup tasks: I need to make a list of redirects for someone to implement (e.g., `/explore` to `/visualize`). I also need to request a new destination for the radiuss.llnl.gov redirect, which has to be done by the Comp web team. A lot of RADIUSS comms materials/assets use that URL so I don't want it to be broken for very long.

@vsoch, months later (sorry), now that you're evaluating RADIUSS projects more closely, do you feel any differently about your proposed changes? Or the same?

**Comment by vsoch** [comment]
Yeah! Let me update each section I wrote earlier:


**pages** I still think this re-org makes sense for the developer to easily find things. 

**search/explore vs. visualize** Just looked again - I'm still thinking my expectation for "explore" is an interface to browse the software, and not a bunch of visualizations. But perhaps Explore should by default (when clicked) go to software, but then have submenus for Software, Visualization (or similar)? If you don't want to have the top level link to anything then I'd just cleanly separate Explore (software) and Visualize (charts).

**RADIUSS** @davidbeckingsale can also comment, but we are working on a new snazzy portal for RADIUSS (that will hopefully be approved for radiuss.llnl.gov). He's out early this week but will be back later in the week and we have the template done, just need to run it by the grandmaster. I would still put it under "About" or similar and give a name that is more easy to understand (aka not an acronym!) :laughing: 

**spelling** is still useful to check I think, but if you don't want it added I won't be too upset. I do think it's important we have some strategy for spell checking if not this suggested one.

**preview** this is still really important for being able to preview changes - I do this for all the webby stuffs I maintain for different orgs.

I think that's it! Let me know if I forgot anything.

**Comment by hauten** [comment]
Awesome @vsoch. Looking forward to the "new snazzy portal"

**Comment by vsoch** [comment]
:sparkles: :sparkles: :sparkles: me too!! :sparkles: :sparkles: :sparkles:

**Review by hauten — APPROVED** [review]
I committed some things too

**Comment by hauten** [comment]
My changes added to Vanessa's:
- Renamed category browse to Explore
- Renamed explore references to Visualize
- Rearranged top-level nav: Explore, Visualize, About, News
- Updated RADIUSS references to point to new paths
- Removed obsolete RADIUSS README

This PR eliminates one major page -- the category browse for RADIUSS -- so the instructions for a repo to add *both* `radiuss` and `whatever category` tags seems outdated. I modified the instructions a bit but didn't explicitly remove this requirement in case we want/need to reinstate it for some later functionality. No point in removing any tags from a RADIUSS repo.

I will update RADIUSS pointers on dev.llnl.gov after these changes are live.

REDIRECTS NEEDED:

@vsoch are you able to redirect this? I fixed it everywhere on this site, but it appears in a PDF on another site. software.llnl.gov/radiuss/ --> software.llnl.gov/explore/#/RADIUSS

I have asked the Comp web team to handle this one sometime today: radiuss.llnl.gov --> software.llnl.gov/explore/#/RADIUSS. We can change it again later, if needed, for the new RADIUSS portal.

**Comment by vsoch** [comment]
@hauten thank you! I'll work with @davidbeckingsale to figure out the redirects / new domain once we get it online. I think he still might be out so ETA later this week or early next week. Thank you again for helping to rebase this old PR!

**Pull request merged**
