### PR TITLE
Updating input_lists.json

### PR DESCRIPTION
**Pull request by salazardetroya**
Adding a new repo to the LLNL organization. This is my first repo added here, please let me know if I need to include something that I forgot. Thanks.

### CODE REVIEW

**Comment by IanLee1521** [comment]
Thanks @salazardetroya !

Question for you though... is there a reason not to add these in to the LLNL organization itself? Usually that is the guidance that IM sends out.

**Comment by salazardetroya** [comment]
> Thanks @salazardetroya !
> 
> Question for you though... is there a reason not to add these in to the LLNL organization itself? Usually that is the guidance that IM sends out.

There is none. I did not know that was a possibility. My apologies.

**Comment by IanLee1521** [comment]
No worries at all! It's pretty straightforward to transfer the repo(s) by following the instructions here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

You'll need to be a member of the LLNL org to do that. If you're not a member, the instructions for joining can be found at: https://software.llnl.gov/about/faq/#how-do-i-join-the-llnl-organization-on-github

**Comment by salazardetroya** [comment]
Thanks. I already added them. I guess it made sense to me to go through a review process to make sure my repo includes the proper license, release number, etc. I will close this one.

**Comment by IanLee1521** [comment]
Awesome, I see the transfers and that means they'll show up in software.llnl.gov after the next update (tonight).

**Pull request closed without merging**
