### PR TITLE
RADIUSS Cleanup

### PR DESCRIPTION
**Pull request by LRWeber**
- Eliminates use of manual subset lists (superseded by use of repo topic tags)
- Addresses additional issues introduced by deletion of `LLNL/hypre` repo as discussed in #355

### CODE REVIEW

**Comment by LRWeber** [comment]
> LGTM, though I'm assuming this works as expected, which I think you will know better than I do... :)

There will still be some broken links from the deleted repo until the update tonight clears it from our data, but after that we should be good.

**Comment by IanLee1521** [comment]
Sounds good.

Do you think we should force a manual update to resolve that?

**Comment by LRWeber** [comment]
I think it's okay to leave it; It would only gain us a few hours, and the same scenario would happen for any other repo that gets deleted in a given day without our foreknowledge.

Plus, all the data is still intact since we don't pull from GitHub's info in real time. It will only impact anyone who specifically tries to click through to that particular GitHub page.

**Comment by IanLee1521** [comment]
Sounds good!

**Comment by aidan-epperly** [comment]
I this may have been expected, but currently the "App Infrastructure" page only shows "axom" and nothing else.
image

**Comment by hauten** [comment]
> I this may have been expected, but currently the "App Infrastructure" page only shows "axom" and nothing else.

It's expected, but issue #280 is out there to see if we can expose Axom's sub-projects. I haven't looked into it.

**Pull request merged**
