### PR TITLE
Added new view and comments

### PR DESCRIPTION
**Pull request by aidan-epperly**
Added first new view. You can now click the circles on the left to change to a new view where repos are connected based on number of shared dependencies.
image
image

### CODE REVIEW

**Comment by LRWeber** [comment]
The visualization switch looks cool, but I'm a bit unsure of what the new view is trying to show.

For example, LLNL/llnl.github.io and ESGF/esgf-docker are closely linked because they both use GitHub Pages and Jekyll.

Is the idea just to cluster projects that use simliar resources/dependencies? VS the original view which explicitly shows each project and dependency?

**Comment by aidan-epperly** [comment]
> The visualization switch looks cool, but I'm a bit unsure of what the new view is trying to show.
> 
> For example, LLNL/llnl.github.io and ESGF/esgf-docker are closely linked because they both use GitHub Pages and Jekyll.
> 
> Is the idea just to cluster projects that use simliar resources/dependencies? VS the original view which explicitly shows each project and dependency?

The purpose is two fold:

First, in the new graph, which is now pictured above, the line weight of a link is actually meaningful. That is because every shared dependency is another link. So, the darker the line is, the more connected they are. This is also useful from a graph visualization perspective, because the more links there are between two nodes, the stronger they are attracted.

Second, in the original visualization, the large clusters of dependencies caused a large number of nodes to be physically distant from each other even though they were closely connected. This is because the force graph has a static force that repels nodes from each other. By removing dependencies from the graph, it is easier to see the relationships between the repos.

**Comment by aidan-epperly** [comment]
> I would recommend changing the appearance/style of the selector. Right now, it looks like just another part of the legend information.
> 
> This might be a good place to use the slider again! Repeating the same input style should be more intuitive than introducing something different for every visualization.

Alright, I added a slider:
image

**Comment by aidan-epperly** [comment]
Squashed

**Comment by IanLee1521** [comment]
Sorry I'm late to teh conversation... my day got away from me...

When there's a moment, could someone just explain the difference between "LLNL Repositories with Dependencies" and "Internal Packages"?

**Comment by aidan-epperly** [comment]
Sure, internal packages are packages that LLNL has made, so they are both repositories which have dependencies and packages that are the dependencies for other repositories.

**Pull request merged**
