### PR TITLE
release highlights for conduit 0.2.0

### PR DESCRIPTION
**Pull request by cyrush**
@IanLee1521 here is a write up about the conduit release, let me know if you need anything else

### CODE REVIEW

**Comment by IanLee1521** [comment]
Tweaked a couple things, post date I usually do as the release date, and if possible I like to mark the code in the post. 

Can you take a quick look to confirm I marked all of and only the actual code "samples" in the post body?

**Comment by cyrush** [comment]
Checked & looks good!

**Comment by cyrush** [comment]
thanks!

**Comment by cyrush** [comment]
@IanLee1521 doens't look like the bullets survived on the main page?

**Comment by IanLee1521** [comment]
Yeah, I opened a ticket with GitHub about that. Need to get a screenshot before I go and try to fix it.

**Comment by IanLee1521** [comment]
Fixed in: https://github.com/LLNL/llnl.github.io/commit/06df3dfadaea453ac9757e8280e040457d168d14

**Comment by IanLee1521** [comment]
I think it wanted the blank line between the paragraph and the list.

**Pull request merged**
