### PR TITLE
news item about conduit 0.2.1 release

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by IanLee1521** [comment]
Looks good thanks!

**Comment by cyrush** [comment]
thanks!

**Comment by IanLee1521** [comment]
Sure thing! Note that due to some of the HTTPS changes, the deploy isn't automatic, but I just manually triggered it. I think the sync time is ~ 15 minutes but I might be off.

**Comment by cyrush** [comment]
good to know, thanks!

**Pull request merged**
