### PR TITLE
Added new functionality to activity line graph

### PR DESCRIPTION
**Pull request by aidan-epperly**
Adds a click event to the line graph that gives a breakdown of the commits for that week. I still have to add a label, but other than that any thoughts?
image

### CODE REVIEW

**Comment by aidan-epperly** [comment]
Label:
image

**Comment by aidan-epperly** [comment]
No dynamic labels:
image
 Any thoughts on which is better?

**Comment by LRWeber** [comment]
I think the smaller labels work better, mostly because the different text sizes skew the perception of the data. The big text stands out more than big slices.

Would it be possible to make the line graph a bit wider so there's less empty space between? It should help the vertical line labels not run into each other too.

**Comment by LRWeber** [comment]
Something else I've noticed is that the new graphs tend to rely on the browser's built in hover text, which often goes unnoticed since it requires the user to stop moving the mouse entirely for a few moments.

Some of the other graphs utilize D3-tip, which makes hover text instantaneous and more pronounced. Could we use that in the newer graphs as well?

**Comment by aidan-epperly** [comment]
> Would it be possible to make the line graph a bit wider so there's less empty space between? It should help the vertical line labels not run into each other too.

Yes, the line graph was mainly shrunk that much so that I could have a good amount of space to work.

> Something else I've noticed is that the new graphs tend to rely on the browser's built in hover text, which often goes unnoticed since it requires the user to stop moving the mouse entirely for a few moments.
> 
> Some of the other graphs utilize D3-tip, which makes hover text instantaneous and more pronounced. Could we use that in the newer graphs as well?

I made this choice mainly for accessibility. I was reading some guides on best practices and one thing that they had mentioned was using titles because accessibility applications can use it as a name. I tried to figure out if there was a way to do this without making the title show on mouseover, but the only way I found would require some reworking because of how d3 works. If you don't think this is an issue, I will use the tooltip.

**Comment by LRWeber** [comment]
> I made this choice mainly for accessibility. I was reading some guides on best practices and one thing that they had mentioned was using titles because accessibility applications can use it as a name.

That's true! Nothing wrong with that, although these kinds of graphs may be too complex to be practical to "read". A general description of the graph as a whole would likely be more informative in those cases.

I was mostly thinking about providing the info to users in general: the circles in the force graph are more meaningful when you can see their titles, the titles for smaller slices of the pie graphs become legible via hover, etc.
The current hover text gives us those advantages! They just aren't as readily apparent/available, so many users are likely to miss out.

**Comment by aidan-epperly** [comment]
I think this is a viable final version:
image
After this, I am going to go back through all of the work that I have done and do a final-ish pass to do some changes like @LRWeber talked about and perhaps clean up some of the code. Pie chart shows on click. I am also having a glitch where on click the tooltip does not go away until another mouseover, but this may be a problem with the tip, I am not sure.

**Comment by LRWeber** [comment]
>I am also having a glitch where on click the tooltip does not go away until another mouseover, but this may be a problem with the tip, I am not sure.

If I had to guess, the D3-tip is probably relying on a mouse-out trigger to close/hide the tooltip. The object in question disappears/moves before the mouse actually leaves the area, so the tooltip gets stuck.
On the next mouseover, either it is set to only allow one tooltip at a time OR there's really only one tooltip that just gets re-positioned and text updated.

I think it's still good to publish for now; That's something we can fix later!

**Comment by aidan-epperly** [comment]
>If I had to guess, the D3-tip is probably relying on a mouse-out trigger to close/hide the tooltip. The object in question disappears/moves before the mouse actually leaves the area, so the tooltip gets stuck.
On the next mouseover, either it is set to only allow one tooltip at a time OR there's really only one tooltip that just gets re-positioned and text updated.

I tried to fix this by calling [tip.hide on click](https://github.com/LLNL/llnl.github.io/blob/master/js/explore/line_repoActivityExplore.js#L202) which is what the mouseout calls, but it didn't work.

**Pull request merged**
