### PR TITLE
Breakdown by repo on click

### PR DESCRIPTION
**Pull request by aidan-epperly**
This PR adds an on click event to the pie charts which allows the user to see the breakdown of commits by the top repos on the individual repo level.

### CODE REVIEW

**Comment by aidan-epperly** [comment]
image

**Comment by aidan-epperly** [comment]
Alright, this should be a full implementation including on click animations:
image
The one thing I can imagine adding is removing the legend on click.

**Comment by LRWeber** [comment]
Is there any way to get labels on the expanded slices? At the higher level, the legend provides enough info without the need to mouse-over. The more detailed view, on the other hand, makes it difficult to identify and compare the different repos.

**Comment by aidan-epperly** [comment]
I was thinking of implementing something along the lines of [this](https://www.d3-graph-gallery.com/graph/donut_label.html) since I am beginning to dislike the sunburst style label on the pie chart if I was to do labels. Does this look good?

**Comment by LRWeber** [comment]
> I was thinking of implementing something along the lines of [this](https://www.d3-graph-gallery.com/graph/donut_label.html) since I am beginning to dislike the sunburst style label on the pie chart if I was to do labels. Does this look good?

That could work.

**Comment by aidan-epperly** [comment]
If you think the in-slice label is good, I can just use that. Definitely has some advantages!

**Comment by LRWeber** [comment]
> If you think the in-slice label is good, I can just use that. Definitely has some advantages!

The in-slice label is fairly easy to read without the extra cognitive load of following the lines. I think it would be safe to use in this case since there's a set number of repos that would be displayed, so it shouldn't be too crowded. Similar to the license sunburst, having labels as tooltips only on the tiny slices would still work well.

**Comment by aidan-epperly** [comment]
Removes the legend and centers on click:
image

**Comment by aidan-epperly** [comment]
I'll get to work implementing the labels.

**Comment by aidan-epperly** [comment]
Labels:
image

**Pull request merged**
