### PR TITLE
Always show as many posts up to twenty

### PR DESCRIPTION
**Pull request by aidan-epperly**
This PR should mostly fix issue #446 by showing as as many posts are are available in a given category up to 20. Also, the all button now starts clicked.

### CODE REVIEW

**Review by LRWeber — CHANGES_REQUESTED** [review]
This may not a desirable solution. By removing the limit from the markdown template, the page generates HTML for _every_ post, even if they aren't all visible. The fact that there exists a separate archive page with this behavior seems to indicate this is not what we want for the non-archive page.


Before
image


After
image

**Comment by aidan-epperly** [comment]
That is true, but you will never see more than 20 on the page as the all button is clicked at load time which limits to 20. If I don't have all, or at least many, of the posts then I couldn't show the 20 most recent of every category.

**Comment by LRWeber** [comment]
> That is true, but you will never see more than 20 on the page as the all button is clicked at load time which limits to 20. If I don't have all, or at least many, of the posts then I couldn't show the 20 most recent of every category.
> 
> I don't believe that this page serves the same purpose as the archive in any way.

It's not so much about what the user sees as it is about performance. That's the only rationale I can think of as to why those pages were separated in the first place; One page loads more quickly to give users a look at the most recent updates, while the other is slower but available if they want to go more in depth. (It isn't too bad now, but it'll keep growing.)

If performance weren't a concern, it could easily have been made as just one page, with collapsible sections like the Archive page has now.

**Comment by aidan-epperly** [comment]
Ok, how about I load only 20 of each?

**Comment by LRWeber** [comment]
> Ok, how about I load only 20 of each?

That may be a better option if possible. It at least limits it to a predictable, finite count! And we can readily adjust that limit if we find it needs it.

**Comment by aidan-epperly** [comment]
Alright, that should do it!

**Comment by aidan-epperly** [comment]
Actually, this broke the archive. Let me fix that first.

**Comment by aidan-epperly** [comment]
Archive should be fixed

**Comment by aidan-epperly** [comment]
I believe those changes would cause the code to no longer limit the number of posts in total.

**Comment by LRWeber** [comment]
> I believe those changes would cause the code to no longer limit the number of posts in total.

Are you sure? I thought with the `{% else %} {% continue %}` it should skip adding the post html if it doesn't fit any of the conditions.

**Comment by aidan-epperly** [comment]
No, you're right. I was confused about where the continue was nested in.

**Review by LRWeber — APPROVED** [review]

**Pull request merged**
