### PR TITLE
Language breakdown for repo subpages

### PR DESCRIPTION
**Pull request by aidan-epperly**
This pr adds a language breakdown for the repo subpages instead of the language word cloud.
image

### CODE REVIEW

**Review by LRWeber — CHANGES_REQUESTED** [review]
Can we change this to use a color scheme that fits more with the rest of the page? Perhaps one similar to licenses pie graph?

**Comment by aidan-epperly** [comment]
> Can we change this to use a color scheme that fits more with the rest of the page? Perhaps one similar to licenses pie graph?

Right now the colors that are used are the same as the ones that are used on GitHub to identify each language, which is why I chose them, but yes, that should be an easy change.

**Comment by aidan-epperly** [comment]
Here is a different color scheme:
image

**Comment by aidan-epperly** [comment]
image

**Review by LRWeber — APPROVED** [review]

**Comment by tzanio** [comment]
Thanks for adding this, it is nice. 

If possible, it will be also interesting to see such breakdown for all the LLNL repos (and also in each Category).

**Pull request merged**
