### PR TITLE
News Archive

### PR DESCRIPTION
**Pull request by hauten**
This is an experiment to see if (1) the site admins like it and (2) I executed it correctly. I attempted to create a new page (News Archive) to house older news posts: 2016 thru Oct 2018. Once 2019 news accumulates for a few months, I'll move the rest of 2018 news into the archive. I figured I would ask forgiveness instead of permission...
file structure

1. Created "news" folder under "llnl.github.io" and moved news.md into it
2. Created "newsarchive" folder under "_posts" & moved older posts into it
3. Created news-archive.md (in new "news" folder) using default layout for news
4. Added link on news.md to News Archive
5. Updated header.html to turn News into a dropdown menu with News Archive as subordinate option

The thing I am least sure about is whether line 7 in news-archive.md will correctly pull in only the posts in the "newsarchive" folder: {% for page in site.posts.newsarchive %}

### CODE REVIEW

**Comment by IanLee1521** [comment]
@hauten -- it looks like there is a problem with the way that it's written up now. Maybe @gonsie could help sort it out?

Right now, it has the "news archive" submenu in the nav bar, but all the articles still show up on the "main" news page.

**Comment by gonsie** [comment]
I just tried this locally and it works great!! Nice job @hauten 😄

**Comment by IanLee1521** [comment]
What if we moved the note at teh top (`For additional information about our open-source activities, see the archive.`) to be a big button at the bottom?

Right now with it at the top of the page, doesn't seem quite as "pop-y"

**Comment by gonsie** [comment]
Also, the travis build is failing due to flake8 on the file `explore/scripts/get_repos_creationhistory.py` ... which is unrelated to this PR.

**Comment by IanLee1521** [comment]
I'll fix the script in master.

**Comment by IanLee1521** [comment]
Actually, I already had... Just merged master into this branch, tests should clear shortly.

**Comment by gonsie** [comment]
snazzy button added! @IanLee1521 please merge once the tests pass.

**Comment by hauten** [comment]
@gonsie or @IanLee1521, the Archive page throws a 404. Is it because we're missing a slash on archive.md? permalink: /news/archive

**Comment by gonsie** [comment]
@hauten it looks like when we link to the archive we are using "/news/archive/" but the permalink is "/news/archive". Either the incoming links or the permalink need to change to be consistent. Can you update it with #132 ?

**Pull request merged**
