### PR TITLE
Update license page

### PR DESCRIPTION
**Pull request by IanLee1521**

### CODE REVIEW

**Comment by tgamblin** [comment]
I wrapped the NOTICE at 80 chars and broke it into clauses.

**Comment by davidbeckingsale** [comment]
Should have wrapped it at 72 😆

**Comment by tgamblin** [comment]
be my guest

**Comment by IanLee1521** [comment]
Here's a question... Do we think these files should be plaintext or Markdown files ?

**Comment by davidbeckingsale** [comment]
This might be frowned upon, but I think markdown format with no extension would be my preference.

**Comment by tgamblin** [comment]
> markdown format with no extension

I frown upon that.  I looked at other projects, like [Rust](https://github.com/rust-lang/rust) and the license-ish files (`LICENSE`, `LICENSE-*`, `COPYRIGHT`, `NOTICE`)  are plain text.  I'd keep them that way for simplicity.

**Comment by tgamblin** [comment]
A semi-random sample of repos at github.com/github turns up plain-text licensy files too.

**Comment by IanLee1521** [comment]
Works for me.

**Comment by IanLee1521** [comment]
Hmm, It looks like that was wrapped to 74 characters... I updated to be actually 80. I also updated the `index.html` page to use the `{% include_relative ... %} macro (https://jekyllrb.com/docs/includes/#including-files-relative-to-another-file) to avoid having duplicate copies of the NOTICE text in the repo.

Give it one more look and let me know if you have any concerns?

**Comment by tgamblin** [comment]
It was wrapped at 78 characters, which is the safe way to wrap for 80-char displays (so that there is some room for a cursor at the end).  I would revert the last commit.

If you look at all the licenses in the same directory, they are much narrower, as well.

**Comment by tgamblin** [comment]
FYI: my motivation for doing this is so that no project has to reformat these files to meet their guidelines.  If you wrap at exactly 80 chars, some will have to reformat.  This is why the licenses are so narrow.

**Comment by IanLee1521** [comment]
Hmm, I'm fine with that goal, but something is odd then, because in your commit:

```
Reference herein to any specific commercial product, process, or service
by trade name, trademark, manufacturer, or otherwise does not necessarily
```

the first line there is 72 characters (plus the newline is 73), but the ` by` should be on that same line (to make it 75 characters + the newline = 76)...

Honestly, I don't really care what it is, but I do want to settle on the ONE version, and know that we agree on what that is, so that we can ensure that all applicable projects match.

**Comment by tgamblin** [comment]
That is likely a heuristic.  If you do what you suggest, the first line is much longer than the second line, but you can't pull a word up from the third line to even it out because the first word on the third line is `constitute`.  It's trying to balance in situations where it has to wrap.

I still propose my prior version.  What's the matter with it?

**Comment by IanLee1521** [comment]
Done. Going to go ahead and merge now.

**Pull request merged**
