### PR TITLE
Open accordions using URL hashes

### PR DESCRIPTION
**Pull request by dpfens**
This change allows users to link directly to an opened accordion.

Page section tracking via URL hash is modified to exclude headings within page accordions, as those headings would override the open accordion's hash on-page.

Also adds a missing `js.map` file.

### CODE REVIEW

**Comment by IanLee1521** [comment]
I admit I'm not the best front end expert, but this seems reasonable to me.

**Review by IanLee1521 — APPROVED** [review]

**Comment by dpfens** [comment]
@IanLee1521 @hauten I just added a change to allow users to manually specify the `id`/`slug` of the accordion, both for SEO purposed, and to avoid potential conflicts with other components on the page

**Review by LRWeber — APPROVED** [review]
Looks like it does what it set out to do! This should resolve #671 

I have included some nitpicky formatting suggestions. We've (unfortunately) yet to establish standards for JS the way we have for Python, but ideally a file should at least be consistent in itself.

**Comment by dpfens** [comment]
Added Matomo tracking code for tracking accordion opens

**Pull request merged**
