### PR TITLE
Update input_lists.json

### PR DESCRIPTION
**Pull request by jerhill**
Add 'nsgcc' (Nanosecond Gated CMOS Camera) project and nsCamera repository
LLNL-CODE- 838080 approved for open source release

### CODE REVIEW

**Comment by LRWeber** [comment]
@jerhill Neither the organization nor the repository seem to exist on GitHub.
Is this a private repository? We can only collect GitHub data for projects/repos that are visible to the public.

**Review by LRWeber — CHANGES_REQUESTED** [review]
Neither the organization nor the repository seem to exist on GitHub.
Is this a private repository? We can only collect GitHub data for projects/repos that are visible to the public.

**Comment by IanLee1521** [comment]
Also, you don't need to provide both the org and the repo links.. Including in the org list means that all (public) repos will be indexed from that organization, while the repos list is for specific one off repositories where you don't want to include the full organization list.

**Comment by jerhill** [comment]
The instructions at https://software.llnl.gov/about/faq/ imply that this is the method to add a new project to github. What is the correct method for adding a new project and repo?

**Comment by LRWeber** [comment]
@jerhill Those instructions are for an existing repository to be included in the https://software.llnl.gov/ listings. You will need to go through the standard steps of creating a GitHub repository and/or organization first. e.g https://github.com/new
Once the repository exists, we can feature it in our catalogue.

**Comment by jerhill** [comment]
I've already created and populated a public repo using that (https://github.com/jerhill/nsCamera), but I don't have permission to transfer ownership to llnl, nor do I know how to specify that it should become 'nsgcc/nsCamera'
I've looked through the help, but I can't find anything about creating an organization.

**Comment by LRWeber** [comment]
You can create a GitHub organization here https://github.com/organizations/new You would need to name the organization `nsgcc` if you want to use `nsgcc/nsCamera`.
If you would like the repo transferred to the LLNL organization instead (as `LLNL/nsCamera`) you can contact open-source@llnl.gov for assistance.

**Comment by jerhill** [comment]
OK, the organization has been created and the repo uploaded. Thanks for your assistance!

**Comment by IanLee1521** [comment]
Thanks @jerhill ! 

Out of curiosity, is there a reason you put it in a new organization, rather than in the LLNL organization?

**Review by LRWeber — APPROVED** [review]

**Review by LRWeber — APPROVED** [review]

**Pull request merged**
